import { TeamMember, Task } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { subDays, addDays } from 'date-fns';

const now = new Date();

export const teamMembers: TeamMember[] = [
  {
    id: 'user-1',
    name: 'Alex Johnson',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'avatar1')?.imageUrl || '',
    skills: ['JavaScript', 'React', 'Node.js', 'UI/UX Design'],
    currentWorkload: 5,
  },
  {
    id: 'user-2',
    name: 'Maria Garcia',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'avatar2')?.imageUrl || '',
    skills: ['Python', 'Machine Learning', 'Data Analysis', 'Databases'],
    currentWorkload: 3,
  },
  {
    id: 'user-3',
    name: 'James Smith',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'avatar3')?.imageUrl || '',
    skills: ['Project Management', 'Agile', 'Scrum', 'Team Leadership'],
    currentWorkload: 7,
  },
  {
    id: 'user-4',
    name: 'Priya Patel',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'avatar4')?.imageUrl || '',
    skills: ['Quality Assurance', 'Test Automation', 'CI/CD', 'DevOps'],
    currentWorkload: 4,
  },
  {
    id: 'user-5',
    name: 'Kenji Tanaka',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'avatar5')?.imageUrl || '',
    skills: ['Go', 'Kubernetes', 'Cloud Infrastructure', 'System Architecture'],
    currentWorkload: 6,
  },
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    title: 'Design initial UI mockups',
    description: 'Create wireframes and high-fidelity mockups for the main dashboard and task views.',
    status: 'Done',
    priority: 'High',
    assignee: teamMembers[0],
    startDate: subDays(now, 10).toISOString(),
    endDate: subDays(now, 5).toISOString(),
    dependencies: [],
  },
  {
    id: 'task-2',
    title: 'Set up project structure and boilerplate',
    description: 'Initialize the Next.js project, set up folders, and install necessary dependencies.',
    status: 'Done',
    priority: 'Urgent',
    assignee: teamMembers[4],
    startDate: subDays(now, 9).toISOString(),
    endDate: subDays(now, 7).toISOString(),
    dependencies: [],
  },
  {
    id: 'task-3',
    title: 'Develop authentication flow',
    description: 'Implement user sign-up, login, and session management.',
    status: 'In Progress',
    priority: 'High',
    assignee: teamMembers[0],
    startDate: subDays(now, 4).toISOString(),
    endDate: addDays(now, 2).toISOString(),
    dependencies: ['task-1', 'task-2'],
  },
  {
    id: 'task-4',
    title: 'Build Kanban board component',
    description: 'Create the UI for the Kanban board with draggable cards and columns.',
    status: 'In Progress',
    priority: 'High',
    assignee: teamMembers[0],
    startDate: subDays(now, 1).toISOString(),
    endDate: addDays(now, 5).toISOString(),
    dependencies: ['task-1'],
  },
  {
    id: 'task-5',
    title: 'Implement AI task assigner API',
    description: 'Develop the Genkit flow and API endpoint for the AI-powered task assignment feature.',
    status: 'To Do',
    priority: 'Medium',
    assignee: teamMembers[1],
    startDate: now.toISOString(),
    endDate: addDays(now, 6).toISOString(),
    dependencies: ['task-2'],
  },
  {
    id: 'task-6',
    title: 'Create Gantt chart visualization',
    description: 'Build the component to display tasks on a timeline with dependencies.',
    status: 'To Do',
    priority: 'Medium',
    assignee: teamMembers[2],
    startDate: addDays(now, 1).toISOString(),
    endDate: addDays(now, 8).toISOString(),
    dependencies: ['task-1'],
  },
  {
    id: 'task-7',
    title: 'Set up automated testing pipeline',
    description: 'Configure CI/CD to run unit and integration tests on every push.',
    status: 'Review',
    priority: 'Low',
    assignee: teamMembers[3],
    startDate: subDays(now, 3).toISOString(),
    endDate: addDays(now, 1).toISOString(),
    dependencies: ['task-2'],
  },
  {
    id: 'task-8',
    title: 'Deploy to staging environment',
    description: 'Set up a staging server and deploy the initial version of the application.',
    status: 'To Do',
    priority: 'High',
    assignee: teamMembers[4],
    startDate: addDays(now, 7).toISOString(),
    endDate: addDays(now, 9).toISOString(),
    dependencies: ['task-3', 'task-4', 'task-5', 'task-6'],
  },
  {
    id: 'task-9',
    title: 'Write user documentation',
    description: 'Create helpful documentation for all features of the application.',
    status: 'To Do',
    priority: 'Low',
    startDate: addDays(now, 2).toISOString(),
    endDate: addDays(now, 10).toISOString(),
    dependencies: [],
  },
];
