import { TeamMember, Task } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { subDays, addDays } from 'date-fns';

const now = new Date();

export const teamMembers: TeamMember[] = [
  {
    id: 'user-1',
    name: 'Alex Johnson',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'avatar1')?.imageUrl || '',
    skills: ['JavaScript', 'React', 'Node.js', 'UI/UX Design', 'Vocal Production'],
    currentWorkload: 5,
  },
  {
    id: 'user-2',
    name: 'Maria Garcia',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'avatar2')?.imageUrl || '',
    skills: ['Python', 'Machine Learning', 'Data Analysis', 'Databases', 'Audio Engineering'],
    currentWorkload: 3,
  },
  {
    id: 'user-3',
    name: 'James Smith',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'avatar3')?.imageUrl || '',
    skills: ['Project Management', 'Agile', 'Scrum', 'Team Leadership', 'Songwriting'],
    currentWorkload: 7,
  },
  {
    id: 'user-4',
    name: 'Priya Patel',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'avatar4')?.imageUrl || '',
    skills: ['Quality Assurance', 'Test Automation', 'CI/CD', 'DevOps', 'Mastering'],
    currentWorkload: 4,
  },
  {
    id: 'user-5',
    name: 'Kenji Tanaka',
    avatarUrl: PlaceHolderImages.find(img => img.id === 'avatar5')?.imageUrl || '',
    skills: ['Go', 'Kubernetes', 'Cloud Infrastructure', 'System Architecture', 'Sound Design'],
    currentWorkload: 6,
  },
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    title: 'Phase 1: Market Research & Feasibility Study',
    description: 'Conduct in-depth market analysis for the new long-term project initiative.',
    status: 'Done',
    priority: 'High',
    assignee: teamMembers[2],
    startDate: '2023-02-15T00:00:00.000Z',
    endDate: '2023-06-30T00:00:00.000Z',
    dependencies: [],
  },
  {
    id: 'task-2',
    title: 'Phase 2: Core Technology Prototyping',
    description: 'Develop and test the core technology stack for the next-generation platform.',
    status: 'Done',
    priority: 'Urgent',
    assignee: teamMembers[4],
    startDate: '2023-07-01T00:00:00.000Z',
    endDate: '2024-01-31T00:00:00.000Z',
    dependencies: ['task-1'],
  },
  {
    id: 'task-3',
    title: 'Alpha Version Development',
    description: 'Full development cycle for the alpha release, including core features.',
    status: 'In Progress',
    priority: 'High',
    assignee: teamMembers[0],
    startDate: '2024-02-01T00:00:00.000Z',
    endDate: '2024-10-31T00:00:00.000Z',
    dependencies: ['task-2'],
  },
  {
    id: 'task-4',
    title: 'Establish Strategic Partnerships',
    description: 'Identify and build relationships with key industry partners.',
    status: 'In Progress',
    priority: 'Medium',
    assignee: teamMembers[2],
    startDate: '2024-05-15T00:00:00.000Z',
    endDate: '2025-01-15T00:00:00.000Z',
    dependencies: ['task-1'],
  },
  {
    id: 'task-5',
    title: 'Beta Program and User Feedback Collection',
    description: 'Launch a closed beta program and systematically gather user feedback.',
    status: 'To Do',
    priority: 'High',
    assignee: teamMembers[3],
    startDate: '2024-11-01T00:00:00.000Z',
    endDate: '2025-04-30T00:00:00.000Z',
    dependencies: ['task-3'],
  },
  {
    id: 'task-6',
    title: 'Infrastructure Scaling & Global Deployment Prep',
    description: 'Upgrade server infrastructure to handle global traffic and prepare for multi-region deployment.',
    status: 'To Do',
    priority: 'Urgent',
    assignee: teamMembers[4],
    startDate: '2025-02-01T00:00:00.000Z',
    endDate: '2025-08-31T00:00:00.000Z',
    dependencies: ['task-3'],
  },
  {
    id: 'task-7',
    title: 'Official Public Launch Campaign',
    description: 'Develop and execute a comprehensive marketing campaign for the public launch.',
    status: 'To Do',
    priority: 'High',
    assignee: teamMembers[3],
    startDate: '2025-09-01T00:00:00.000Z',
    endDate: '2025-12-31T00:00:00.000Z',
    dependencies: ['task-5', 'task-6'],
  },
  {
    id: 'task-8',
    title: 'Gen 2 Feature Planning',
    description: 'Research and plan the feature set for the second generation of the product.',
    status: 'To Do',
    priority: 'Medium',
    assignee: teamMembers[1],
    startDate: '2026-01-15T00:00:00.000Z',
    endDate: '2026-07-31T00:00:00.000Z',
    dependencies: ['task-7'],
  },
  {
    id: 'task-9',
    title: 'Internationalization & Localization (I18n & L10n)',
    description: 'Adapt the platform for multiple languages and regions.',
    status: 'To Do',
    priority: 'Medium',
    assignee: teamMembers[0],
    startDate: '2026-08-01T00:00:00.000Z',
    endDate: '2027-02-28T00:00:00.000Z',
    dependencies: ['task-8'],
  },
  {
    id: 'task-10',
    title: 'Long-term AI Strategy Development',
    description: 'Define the 5-year AI and Machine Learning strategy for the company.',
    status: 'To Do',
    priority: 'Low',
    assignee: teamMembers[1],
    startDate: '2027-03-01T00:00:00.000Z',
    endDate: '2027-11-30T00:00:00.000Z',
    dependencies: ['task-9'],
  },
];
